import fs from "fs";
import path from "path";

const version = `qclub-${Date.now()}`;
const generatedAt = new Date().toISOString();

const versionFilePath = path.resolve("public/version.json");
const buildVersionModulePath = path.resolve("src/generated/qclub-build-version.js");

const versionData = {
  version,
  generatedAt,
};

fs.mkdirSync(path.dirname(buildVersionModulePath), { recursive: true });

fs.writeFileSync(
  versionFilePath,
  JSON.stringify(versionData, null, 2)
);

fs.writeFileSync(
  buildVersionModulePath,
  [
    "// Generated by scripts/update-version.js before every production build.",
    `export const QCLUB_BUILD_VERSION = ${JSON.stringify(version)};`,
    `export const QCLUB_BUILD_GENERATED_AT = ${JSON.stringify(generatedAt)};`,
    "",
  ].join("\n")
);

console.log("Q Club version.json updated:", version);
